version: '3.3'
services:
  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employeedb
    expose:
      - 3306
    
  ot-go-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      DB_URL: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
     - 8080:8080
