 
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/conf.d
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employeedb
    ports:
      - "3306:3306"
    networks:
      - elk

  ot-go-webapp:
    image: opstreedevops/ot-go-webapp:filebeat
    volumes:
      - type: bind
        source: ./ot-go-webapp/filebeat.yml
        target: /etc/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: ./ot-go-webapp/entrypoint.sh
        target: /app/entrypoint.sh
    ports:
      - "8080:8080"
    environment:
      DB_URL: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
    entrypoint:
      - ./entrypoint.sh
    networks:
      - elk
    depends_on:
      - mysql

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
