---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  ports:
  - name: {{ .Values.mysql.name }}
    port: {{ .Values.mysql.port }}
  clusterIP: None
  selector:
    app: {{ .Values.mysql.name }}
